const ScreenNames = {
  WELCOME: 'WelcomeScreen',
  STARTED: 'StartedScreen',
  INSTRUCTION: 'InstructionScreen',
  SETUP_PASSCODE: 'SetupPasscode',
  MNEMONICS: 'MnemonicsScreen',
  BACKUP_MNEMONICS: 'BackupMnemonics',
  IMPORTSCREEN1: 'ImportScreen1',
  DISCOVERSCREEN: 'DiscoverScreen',
  MULTICOINWALLET: 'MultiCoinWallet',
  WALLETSETUP: 'Walletsetup',
  SCANSCREEN:'Scan',
  IMPORTSCREEN2: 'ImportScreen2',
  NFT_Screen: 'NftScreen',
  BACKUPWALLET: 'BackupWallet',
  IMPORTSCREEN3: 'ImportScreen3',
  SELECTASSET: 'SelectAsset',
  PUSHNOTIFICATION: 'PushNotification',
  PREFERENCES: 'Preferences',
  CURRENCY: 'Currency',
  SWAPSCREEN: 'Swap',
  SECURITY: 'Security',
  WALLETCONNECT: 'WalletConnect',
  SPLASHSCREEN: 'SplashScreen',
  MNEMONICS_FIELDS: 'MnemonicsFields',
  NODESETTINGS: 'NodeSettings',
  WALLETDETAIL: 'WalletDetail',
  RECIEVESCREEN: 'RecieveScreen',
  PRICEALERTS: 'PriceAlerts',
  HOMESCREEN: 'Home',
  EMPTYWALLET: 'EmptyWallet',
  NOTIFICATION: 'NotificationScreen',
  RECIEVECOINS: 'RecieveCoin',
  BUYCOIN: 'BuyCoin',
  PAYMENT: 'PaymentScreen',
  SENDSCREEN: 'SendScreen',
  ADD_TOKENS: 'AddTokens',
  BUYSCREEN: 'BuyScreen',
  LOADING: 'Loading',
  ADD_MAINNET: 'AddMainnet',

};
export default ScreenNames;
